env:
  - NODE_ENV="production"
language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches --add origin master && git fetch
install: NODE_ENV=development npm ci
deploy:
  provider: npm
  on:
    branch: feature/npm-publish-test
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
