env:
  - NODE_ENV="production"
language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - git remote set-branches --add origin master && git fetch
install: NODE_ENV=development npm ci
jobs:
  include:
    - stage: Push image
      script: ./scripts/docker-push-prod.sh
      on:
        branch: feature/npm-publish-test
