env:
  - NODE_ENV="production"
language: node_js
node_js:
  - "12"
services:
  - docker
before_install:
  # Create a master branch for commitlint
  # https://github.com/conventional-changelog/commitlint/issues/6
  - chmod +x ./scripts/docker-push-prod.sh
  - git remote set-branches --add origin master && git fetch
install: NODE_ENV=development npm ci
jobs:
  include:
    - stage: build docker prod image
      script:
        - docker build -t infoxicator/one-app-test:v5.0.8
        - docker cp $(docker create infoxicator/one-app-test:v5.0.8):opt/one-app/build ./one-app-statics
        - ./scripts/docker-push-prod.sh
      on:
        branch: feature/npm-publish-test
    - stage: Deploy Statics
      before_deploy:
      - cd one-app-statics
      deploy:
        provider: npm
        email: $NPM_EMAIL_ADDRESS
        api_key: $NPM_AUTH_TOKEN
        on:
          branch: feature/npm-publish-test
